deadlinekiller/deadlinekiller/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    # Home Page
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home_page'),

    # Apps Urls
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^deadlines/', include('deadlines.urls', namespace='deadlines')),
    url(r'^teams/', include('teams.urls', namespace='teams')),
    url(r'^friends/', include('friends.urls', namespace='friends')),
    

]

deadlinekiller/friends/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [


    url(r'^connections/$', views.Connections.as_view(), name='connections'),
    # All friends
    url(r'^all/$', views.FriendsListView.as_view(), name='friends_list'),
    # Invitations
    url(r'^invitations/$', views.FriendsInvitationsView.as_view(), name='friends_invitations'),
    # Accept invitation
    url(r'^accept/$', views.AcceptConnectionView.as_view(), name='accept_connection'),
    
    url(r'^make-connection/$', views.MakeConnectionView.as_view(), name='make_connection'),
    url(r'^delete-connection/(?P<pk>\d+)/$', views.DeleteConnectionView.as_view(), name='delete_connection'),


    
    

]

deadlinekiller/teams/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
	
    url(r'^team-list/$', views.TeamListView.as_view(), name='team_list'),
    url(r'^team-detail/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.TeamDetailView.as_view(), name='team_detail'),
    url(r'^team-create/$', views.TeamCreateView.as_view(), name='team_create'),
    url(r'^team-delete/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.TeamDeleteView.as_view(), name='team_delete'),

    #Adding to the team and removing from the team (user profile)
    url(r'^team-add/$', views.AddToTheTeamView.as_view(), name='add_to_the_team'),
    

]

deadlinekiller/friends/models.py
from django.contrib.auth.models import User
from django.db import models


class Connection(models.Model):
	 created = models.DateTimeField(auto_now_add=True, editable=False)
	 creator = models.ForeignKey(User, related_name='friendship_creator_set')
	 following = models.ForeignKey(User, related_name='friend_set')
	 accepted = models.BooleanField(default=False)

	 def __str__(self):
	 	return 'Connection between {} and {}'.format(str(self.creator.username), str(self.following.username))

deadlinekiller/friends/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import Q
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DeleteView, ListView, View

from .models import Connection 

from account.models import Profile


class Connections(LoginRequiredMixin, ListView):
	model = Connection
	template_name = 'friends/connections_list.html'
	context_object_name = 'connections'

	def get_context_data(self, **kwargs):
		context = super(Connections, self).get_context_data()
		query = self.request.GET.get("q")
		if query:
			# Get potentially new friends
			users = User.objects.filter(
										Q(username__icontains=query) | 
										Q(email__icontains=query) |
										Q(first_name__icontains=query) |
										Q(last_name__icontains=query) | 
										Q(profile__date_of_birth__icontains=query) 
										).distinct().exclude(pk=self.request.user.pk) # add profile bio lookup in future
			

			# Exclude users that are already friends with request.user (We want to see only users that are not our friends yet)
			# Get user onnections
			user_connections = Connection.objects.filter(Q(creator=self.request.user)|
														 Q(following=self.request.user))
			
			# Create list of users from connections
			connected_users = []
			for i in user_connections:
				connected_users.append(i.creator)
				connected_users.append(i.following)
			connected_users = set(connected_users)

			# Remove connected users from users in search results
			for user in connected_users:
				# if user is in connected users, remove it form users
				try:
					# Create new users queryset
					users = users.exclude(username=user.username)
				except:
					continue

			# Put users into the context
			context['users'] = users	

		# Getting friends ( filtering in template - change it)

		# Try to get followers and and connected by Profile methods
		# Connection.creator
		con = self.request.user.profile.get_connections()
		# Connection.following
		foll = self.request.user.profile.get_followers()
	
		# All logged in user connections
		connections = con | foll
		connections = connections.filter(accepted=True)	
		number_of_friends = connections.count()
		connections = connections[0:2]
		

		# Connections
		context['friends'] = connections
		# Number of friends
		context['friends_quantity'] = number_of_friends
		return context


class FriendsListView(LoginRequiredMixin, ListView):
	model = Connection
	template_name = 'friends/friends_list.html'
	context_object_name = 'friends'


	def get_context_data(self, **kwargs):
		context = super(FriendsListView, self).get_context_data()
		# Getting friends ( filtering in template - change it)

		# Try to get followers and and connected by Profile methods
		# Connection.creator
		con = self.request.user.profile.get_connections()
		# Connection.following
		foll = self.request.user.profile.get_followers()

		connections = con | foll
		connections = connections.filter(accepted=True)
		number_of_friends = connections.count()
		context['friends_quantity'] = number_of_friends
		context['friends'] = connections
		return context


class MakeConnectionView(LoginRequiredMixin, View):
	
	def post(self, request,  *args, **kwargs):
		user = User.objects.get(username=request.user)
		following = User.objects.get(username=request.POST['friend'])
		
		# Create new connection
		connection = Connection.objects.create(creator=user, following=following)
		return redirect('friends:connections')


class DeleteConnectionView(LoginRequiredMixin, DeleteView):
	model = Connection
	success_url = reverse_lazy('friends:connections')


class FriendsInvitationsView(LoginRequiredMixin, ListView):
	model = Connection
	template_name = 'friends/invitations_list.html'
	context_object_name = 'invited_friends'


	def get_context_data(self, **kargs):
		context = super(FriendsInvitationsView, self).get_context_data()
		# users i invited
		invited_by_me = self.request.user.profile.get_connections().filter(accepted=False)
		# users inviteted me
		invited_me = self.request.user.profile.get_followers().filter(accepted=False)
		context['invited_by_me'] = invited_by_me
		context['invited_me'] = invited_me
		return context



class AcceptConnectionView(LoginRequiredMixin, View):
	""" 
	Accept and declin invitation view 
	"""
	
	def post(self, request, *args, **kwargs):
		# Accept case
		if request.POST.get('status') == 'accept':
			con_pk = request.POST.get('pk')
			# Get Connection from DB
			con = get_object_or_404(Connection, pk=con_pk)
			con.accepted = True
			# Send information to user who invited me, that i accepted his invitation --------TO DO
			con.save()
		# Decline case
		if request.POST.get('status') == 'decline':
			# Get Connection object and delete it
			con = get_object_or_404(Connection, pk=request.POST.get('pk')).delete()			
		return redirect('friends:friends_invitations')
 

 

deadlinekiller/friends/templates/friends/connection_confirm_delete.html
{% extends 'base.html '%}

{% block title %}Are you sure?{% endblock %}

{% block content %}

<h1>Are you sure?</h1>


<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to end friend ship beetween you and: "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

{% endblock %}

deadlinekiller/friends/templates/friends/connections_list.html
{% extends 'base.html' %}


{% block title %}{% endblock %}


{% block content %}

	
	<!-- header -->
	<div class="row">
		<div class="col-12">
			<h1>All connections Test</h1>
		</div>

	</div>
	

	
	<div class="row">
		<!-- All connections (all friends) -->
		<div class="col-6">
			{% if friends %}
			<h2>Your Friends. <a href="{% url 'friends:friends_list' %}">See all your friends.</a></h2>
			<p><small>{% if friends %}You have {{ friends_quantity }} friends.{% endif %}</small></p>
			<p><small><a href="{% url 'friends:friends_invitations' %}">Check </a>for invitations</small></p>
		
				{% for friend in friends %}
					{% if friend.creator != request.user %}
						<div class="card" style="width: 40rem;">
							  <div class="card-body">
								    <h4 class="card-title"><a href="{{ friend.following.profile.get_absolute_url }}">{{ friend.following }}</h4>
								    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
								    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
								    <a href="{% url 'friends:delete_connection' friend.pk %}" class="card-link">Remove friend</a>
								    
							  </div>
						</div>

						<p>{{ friend.creator }}</p>
						
					{% endif %}
					<div class="card" style="width: 40rem;">
							  <div class="card-body">
								    <h4 class="card-title"><a href="{{ friend.following.profile.get_absolute_url }}">{{ friend.following }}</a></h4>
								    <h6 class="card-subtitle mb-2 text-1muted">Card subtitle</h6>
								    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
								    <a href="{% url 'friends:delete_connection' friend.pk  %}" class="card-link">Remove friend</a>
								    
							  </div>
						</div>

						
						
				{% endfor %}	

			{% else %}
				<h1>You don't have any friends yet</h1>
				<p>Make some friendships!</p>
			{% endif%}
		</div>
		
		<!-- Search results and form -->
		<div class="col-6">
			<h2>Find new friends:</h2>
				<form method="get" action="">
					<input type="text" name="q" placeholder="Search friends" value="{{ request.GET.q }}">
					<input type="submit" value="Search">
				</form>
				<hr/>
			{% if users %}
			<h2>Search results</h2>
				<ul>
					{% for user in users %}
						<li>
						<p>{{ user.username}} </p>
						<p>{% include 'friend_form.html' with friend_name=user.username %}</p>
						<hr/>
						</li>
					{% endfor %}
				</ul>
			{% else %}
				<p>No friends so far... click search to find new ones!</p>
			{% endif %}
		</div>	
	</div>

	
{% endblock %}

deadlinekiller/friends/templates/friends/friends_list.html
{% extends 'base.html' %}



{% block title %}All Friends{% endblock %}

{% block content %}
	<h1>All friends</h1>
	<p>You have {{ friends_quantity }} friends</p>
	{% for friend in friends %}
					{% if friend.creator != request.user %}
						<div class="card" style="width: 40rem;">
							  <div class="card-body">
								    <h4 class="card-title"><a href="{{ friend.following.profile.get_absolute_url }}">{{ friend.following }}</h4>
								    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
								    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
								    <a href="{% url 'friends:delete_connection' friend.pk %}" class="card-link">Remove friend</a>
								    
							  </div>
						</div>

						<p>{{ friend.creator }}</p>
						
					{% endif %}
					<div class="card" style="width: 40rem;">
							  <div class="card-body">
								    <h4 class="card-title"><a href="{{ friend.following.profile.get_absolute_url }}">{{ friend.following }}</a></h4>
								    <h6 class="card-subtitle mb-2 text-1muted">Card subtitle</h6>
								    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
								    <a href="{% url 'friends:delete_connection' friend.pk  %}" class="card-link">Remove friend</a>
								    
							  </div>
						</div>
	{% endfor %}
{% endblock %}

deadlinekiller/friends/templates/friends/invitations_list.html
{% extends 'base.html' %}

{% block title %}Invitations{% endblock %}

{% block content %}
	<h1>Friends invitations</h1>
	

	<h2>Invited by me:</h2>
		<ul>
			{% for i in invited_by_me%}
				<li>{{ i.following.username }} | <small>waiting...</small></li>
			{% endfor %}
		</ul>

	<h2>Invited me:</h2>
		<ul>
			{% for j in invited_me%}
				<li>
					<div>
						<h2>{{ j.creator.username }}</h2>
							<div style="display: inline-block;">
								{% include 'accept_form.html' with pk=j.pk %}
							</div>
							<div style="display: inline-block;">								
								{% include 'decline_form.html' with pk=j.pk %}
							</div>
					</div>				
			{% endfor %}
		</ul>
{% endblock %}