deadlinekiller/deadlinekiller/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    # Home Page
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home_page'),

    # Apps Urls
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^deadlines/', include('deadlines.urls', namespace='deadlines')),
    url(r'^teams/', include('teams.urls', namespace='teams')),
    url(r'^friends/', include('friends.urls', namespace='friends')),
    

]

deadlinekiller/teams/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
	
    url(r'^team-list/$', views.TeamListView.as_view(), name='team_list'),
    url(r'^team-detail/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.TeamDetailView.as_view(), name='team_detail'),
    url(r'^team-create/$', views.TeamCreateView.as_view(), name='team_create'),
    url(r'^team-delete/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.TeamDeleteView.as_view(), name='team_delete'),

    #Adding to the team and removing from the team (user profile)
    url(r'^team-add/$', views.AddToTheTeamView.as_view(), name='add_to_the_team'),
    

]

deadlinekiller/teams/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Team(models.Model):
	name = models.CharField(max_length=80)
	slug = models.SlugField(max_length=80)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	creator = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='teams', blank=True, null=True)
	


	def __str__(self):
		return self.name


	def get_absolute_url(self):
		return reverse('teams:team_detail', args=[self.pk, self.slug])

deadlinekiller/teams/forms.py
from django import forms

from .models import Team

class TeamCreationForm(forms.ModelForm):
	class Meta:
		model = Team
		fields = ('name',)
		

deadlinekiller/teams/views.py
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.views.generic import ListView, CreateView, DetailView, DeleteView, View

from .forms import TeamCreationForm
from .models import Team
from account.models import Profile
from friends.models import Connection


class TeamListView(LoginRequiredMixin, ListView):
	model = Team
	context_object_name = 'teams'
	template_name = 'teams/team_list.html'


	def get_queryset(self):
		return Team.objects.filter(creator=self.request.user) 

	def get_context_data(self, *args, **kwargs):
		context = super(TeamListView, self).get_context_data()
		# Get all teams that user.profile is a member of
		teams_of_user = Team.objects.filter(profile=self.request.user.profile)
		# Put teams of user into a context
		context['teams_of_user'] = teams_of_user
		return context


class TeamCreateView(LoginRequiredMixin, CreateView):
	form_class = TeamCreationForm
	template_name = 'teams/team_create.html'


	def form_valid(self, form):
		# Setting up loggedin user as an team creator
		form.instance.creator = self.request.user
		# Setting up slug field
		form.instance.slug = slugify(form.instance.name)
		return super(TeamCreateView, self).form_valid(form)


class TeamDetailView(LoginRequiredMixin, DetailView):
	model = Team
	template_name = 'teams/team_detail.html'

	def get_context_data(self, *args, **kwargs):
		context = super(TeamDetailView, self).get_context_data()
		
		# Get all team members
		team = self.get_object()
		team_members = team.profile_set.all()
		context['team_members'] = team_members

		# Search for users who will be added to the team
		query = self.request.GET.get('q')
		if query:
			#Search within connections (search for friends)
			con = self.request.user.profile.get_connections()
			foll = self.request.user.profile.get_followers()
			all_friends = con | foll

			#Filter form friends
			# If somebody search for users
			users = all_friends.filter(
										Q(creator__username__icontains=query) | 
										Q(following__username__icontains=query)  
										#Q(email__icontains=query) |
										#Q(first_name__icontains=query) |
										#Q(last_name__icontains=query) | 
										#Q(profile__date_of_birth__icontains=query) 
										).distinct().exclude(pk=self.request.user.pk) # add profile bio lookup in future) 			
			
			# Check if user is a team member allready and remove it from results
			for c in users:
				if c.creator.profile in team_members:
					users = users.exclude(pk=c.pk)

				elif c.following.profile in team_members:
					users = users.exclude(pk=c.pk)
			context['users'] = users
		else:
			# Get all your connections (friends) 
			con = self.request.user.profile.get_connections()
			foll = self.request.user.profile.get_followers()
			# Get all connections together 
			all_friends = con | foll

			# Check if friend is a team member allready and remove it from results
			for c in all_friends:
				if c.creator.profile in team_members:
					all_friends = all_friends.exclude(pk=c.pk)

				elif c.following.profile in team_members:
					all_friends = all_friends.exclude(pk=c.pk)			
			context['users'] = all_friends
		return context


class TeamDeleteView(LoginRequiredMixin, DeleteView):
	model = Team
	template_name = 'teams/team_delete.html'
	success_url = reverse_lazy('teams:team_list')


class AddToTheTeamView(LoginRequiredMixin, View):
	'''
	This view adds a user (his profile) to the team
	and removes it.
	'''

	def post(self, request, *args, **kwargs):
		# Case 1 add team member
		if request.POST.get('status') == 'add':

			# Get a team
			team = get_object_or_404(Team, pk=request.POST.get('team_pk'))
			# Get connection
			connection = get_object_or_404(Connection, pk=request.POST.get('con_pk'))

			# Get user from connection
			creator = connection.creator
			following = connection.following

			# Get user that is not a logged in user
			if creator == request.user:
				new_member = following
			else:
				new_member = creator
			# Add new user profile to the team
			team.profile_set.add(new_member.profile)
			team.save()

		# Case 2 remove team member
		elif request.POST.get('status') == 'remove':
			
			# Get a team
			team = get_object_or_404(Team, pk=request.POST.get('team_pk'))
			
			# Get a profile
			profile = get_object_or_404(Profile, pk=request.POST.get('profile_pk'))
			
			# Remove given profile from the team
			team.profile_set.remove(profile)
		
		return redirect('teams:team_list')

deadlinekiller/teams/templates/teams/add_to_team.html
<form action="{% url 'teams:add_to_the_team' %}" method="post">
	<input type="hidden" name="status" value="add">
	<input type="hidden" name="team_pk" value="{{ team_pk }}">
	<input type="hidden" name="con_pk" value="{{ con_pk }}">
	{% csrf_token %}
	<input type="submit" value="Add to the team" class="btn btn-success">
</form>

deadlinekiller/teams/templates/teams/remove_from_team.html
<form action="{% url 'teams:add_to_the_team' %}" method="post">
	<input type="hidden" name="status" value="remove">
	<input type="hidden" name="team_pk" value="{{ team_pk }}">
	<input type="hidden" name="profile_pk" value="{{ profile_pk }}">
	{% csrf_token %}
	<input type="submit" value="Remove from the team" class="btn btn-warning">
</form>

deadlinekiller/teams/templates/teams/team_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Create team{% endblock %}


{% block content %}
	<div class="row">


		<div class="col-4"> 
			<h1>Create new team</h1>
			<form action="" method="post">
				{{ form|crispy }}
				{% csrf_token %}
				<input type="submit" value="Create new team">
			</form>
		</div>


		<div class="col-2"><!-- empty div, free space--></div>


		<div class="col-6">
			<h2>Fill the form and manage!</h2>
			<p>Teams help to manage your tasks and deadlines.</p>
		</div>
		

	</div>

	

{% endblock %}

deadlinekiller/teams/templates/teams/team_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Delete team{% endblock %}


{% block content %}

	<form action="" method="post">{% csrf_token %}
    	<p>Are you sure you want to delete "{{ object }}"?</p>
    	<input type="submit" value="Confirm" />
	</form>



{% endblock %}

deadlinekiller/teams/templates/teams/team_detail.html
{% extends 'base.html' %}

{% block title %}Deadlinekillers | {{ team.name }}{% endblock %}

{% block content%}


	<div class="row">
		<div class="col-12">
			<h2>Team: {{ team.name }}</h2>
			<p><small>Boss (creator): <a class="badge badge-primary" href="{{ team.creator.profile.get_absolute_url }}">{{ team.creator }}</a></small></p>
		</div>
		
	</div>


	<div class="row">
			

			<div class="col-6">
				{% if team_members %}
					<h3>Members:</h3>
					<p>All team members here</p>
					<ul>
						{% for member in team_members %}
							<li>{{ member.user.username }} 
								{% if request.user == team.creator or request.user == member.user %}
									{% include 'teams/remove_from_team.html' with team_pk=team.pk profile_pk=member.pk %}</li>
								{% endif %}
						{% endfor %}
					</ul>
				{% else %}
					<h3>There is nobody in this team</h3>
					<p>Add some friends to this team and work together!</p>
				{% endif %}
			</div>
			

			<div class="col-6">
					<form action="" method="get">
						<p>Search for new team members</p>
						<input type="text" name='q' >
						{% csrf_token %}
						<input type="submit" value="Search" class="btn btn-primary">
					</form>
			</div>


	</div>

	<hr/>
		
	<div class="row">
		

		<div class="col-12">
			<h3>Choose a new team member from your friends</h3>
			{% if users %}
				<ul>
				{% for u in users %}
					<li>{{u}} | {% include 'teams/add_to_team.html' with team_pk=team.pk con_pk=u.pk %}</li>
				{% endfor %}
				</ul>
			{% else %}
				<p>no users</p>
			{% endif %}	
		</div>


	</div>

	<hr/>
		
	<div class="row">
		

		<div class="col-6">
			<p><a class="badge badge-danger" href="{% url 'teams:team_delete' team.pk team.slug %}">Delete</a> this Team.</p>
		</div>


		<div class="col-6">
			<p>Back to <a class="badge badge-primary" href="{% url 'teams:team_list' %}">teams</a>.</p>
		</div>


	</div>
	

{% endblock %}

deadlinekiller/teams/templates/teams/team_list.html
{% extends 'base.html' %}


{% block title %}Deadlines Teams{% endblock %}


{% block content %}
	<div class="row">


			<div class="col-12">
				<h1>Teams list</h1>
			</div>
			


	</div>


	<div class="row">
			

			<div class="col-2 offset-10">
				<p><a href="{% url 'teams:team_create' %}" class="badge badge-info">Create</a> new team.</p>
			</div>


	</div>


	<div class="row">


		<div class="col-6">
			{% if teams %}
				<h2>You have {% if teams.count > 1 %}<span class="badge badge-pill badge-primary">{{ teams.count }}</span> teams:{% else %}<span class="badge badge-pill badge-primary">{{ teams.count }}</span> team:{% endif %}</h2>
				<div class="list-group">
					{% for team in teams %}
						<a href="{% url 'teams:team_detail' team.pk team.slug %}" class="list-group-item list-group-item-action">{{ team.name }}</a></li>
					{% endfor %}
					</ul>
				</div>
			{% else %}
				<h2>Need a team? Create one!</h2>
				<p>You are not a member of any team. <a href="#">Join</a> the existing one or <a href="{% url 'teams:team_create' %}">create</a> yours.</p>
			{% endif %}
		</div>


		<div class="col-6">
			{% if teams_of_user %}
				<h2>You are a member of {% if teams_of_user.count > 1 %}<span class="badge badge-pill badge-primary">{{ teams_of_user.count }}</span> teams{% else %}<span class="badge badge-pill badge-primary">{{ teams_of_user.count }}</span> team:{% endif %}</h2>
				<div class="list-group">
					{% for team in teams_of_user %}
						<a href="{{ team.get_absolute_url }}" class="list-group-item list-group-item-action">{{ team }}</a>
					{% endfor %}
				</div>
			{% else %}
				<p>You are not member of any team yet.</p>
			{% endif %}

		</div>


	</div>


{% endblock %}