deadlinekiller/account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views



urlpatterns = [
    #url(r'^login/$', views.user_login, name='login'),
    
    # Login view
    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    # Logout view
    url(r'^logout/$',  auth_views.LogoutView.as_view(), name='logout'),
    # Logout then login
    url(r'^logout-then-login/$', auth_views.logout_then_login, name='logout_than_login'),

    # Password change
    url(r'^password-change/$', auth_views.PasswordChangeView.as_view(), name='password_change'),
    url(r'^password-change/done/$', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    
    # Resetting password 	
    url(r'^password-reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password-reset/done$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^password-reset/complete/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # Register user
    url(r'^register/$', views.register, name='register'),
    url(r'^edit/$', views.edit, name='edit'),

    # Show user profile
    url(r'^profile/(?P<pk>\d+)/$', views.ProfileView.as_view(), name='profile'),






    # TEST URL
    url(r'^test-home/$', views.test_home, name='test_home'),
]

deadlinekiller/deadlinekiller/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    # Home Page
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home_page'),

    # Apps Urls
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^deadlines/', include('deadlines.urls', namespace='deadlines')),
    url(r'^teams/', include('teams.urls', namespace='teams')),
    url(r'^friends/', include('friends.urls', namespace='friends')),
    

]

deadlinekiller/deadlines/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
	# Deadline CRUD

	# List view
    url(r'^$', views.deadline_list, name='deadline_list'),

    # Detail view
    url(r'^(?P<pk>\d+)/(?P<slug>[-\w]+)/$', views.deadline_detail, name='deadline_detail'),

    # Create
    url(r'^deadline-create/$', views.deadline_create, name='deadline_create'),

    # Update
    url(r'^deadline-update/(?P<pk>\d+)/(?P<slug>[-\w]+)/$', views.deadline_update, name='deadline_update'),
    
    # Delete
    url(r'^deadline-delete/(?P<pk>\d+)/(?P<slug>[-\w]+)/$', views.deadline_delete, name='deadline_delete'),

   
]

deadlinekiller/friends/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [


    url(r'^connections/$', views.Connections.as_view(), name='connections'),
    # All friends
    url(r'^all/$', views.FriendsListView.as_view(), name='friends_list'),
    # Invitations
    url(r'^invitations/$', views.FriendsInvitationsView.as_view(), name='friends_invitations'),
    # Accept invitation
    url(r'^accept/$', views.AcceptConnectionView.as_view(), name='accept_connection'),
    
    url(r'^make-connection/$', views.MakeConnectionView.as_view(), name='make_connection'),
    url(r'^delete-connection/(?P<pk>\d+)/$', views.DeleteConnectionView.as_view(), name='delete_connection'),


    
    

]

deadlinekiller/teams/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
	
    url(r'^team-list/$', views.TeamListView.as_view(), name='team_list'),
    url(r'^team-detail/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.TeamDetailView.as_view(), name='team_detail'),
    url(r'^team-create/$', views.TeamCreateView.as_view(), name='team_create'),
    url(r'^team-delete/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.TeamDeleteView.as_view(), name='team_delete'),

    #Adding to the team and removing from the team (user profile)
    url(r'^team-add/$', views.AddToTheTeamView.as_view(), name='add_to_the_team'),
    

]

deadlinekiller/account/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

from friends.models import Connection
from teams.models import Team



class Profile(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL)
	date_of_birth = models.DateField(blank=True, null=True)
	photo = models.ImageField(upload_to='users/%Y/%m/%d', blank=True)
	# In future (# add profile bio lookup in future in friends app)
	bio = models.TextField(blank=True, null=True)

	# from Teams app
	team = models.ManyToManyField(Team, blank=True)


	def get_connections(self):
		connections = Connection.objects.filter(creator=self.user)
		return connections


	def get_followers(self):
		followers = Connection.objects.filter(following=self.user)
		return followers


	def __str__(self):
		return 'Profile of: {}'.format(self.user.username)

	def get_absolute_url(self):
		return reverse('account:profile', args=[self.pk])

deadlinekiller/account/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Profile


class LoginForm(forms.Form):
	'''
	Old form
	'''
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
	password = forms.CharField(label='Password', widget=forms.PasswordInput)
	password2 = forms.CharField(label='Enter password again', widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ('username', 'first_name', 'email')

	def clean_password2(self):
		cd = self.cleaned_data
		if cd['password'] != cd['password2']:
			raise forms.ValidationError('Passwords are not identical')
		return cd['password2']


class UserEditForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ('date_of_birth', 'photo',)

deadlinekiller/account/views.py
from django.contrib.auth import authenticate, login 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import DetailView

from .forms import LoginForm, UserRegistrationForm, UserEditForm, ProfileEditForm
from .models import Profile



class ProfileView(LoginRequiredMixin, DetailView):
	model = Profile
	template_name = 'account/profile_detail.html'



def user_login(request):
	if request.method == 'POST':
		form = LoginForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			user = authenticate(username=cd['username'],
								password=cd['password'])
			if user is not None:
				if user.is_active:
					login(request, user)
					return HttpResponse('Authentication succeeded')
				else:
					return HttpResponse('Account is blocked')
			else:
				return HttpResponse('Wrong authentication data')
	else:
		form = LoginForm()
	return render(request, 'account/login.html', {'form' : form})



def register(request):
	if request.method == 'POST':
		user_form = UserRegistrationForm(request.POST) 
		if user_form.is_valid():
			new_user = user_form.save(commit=False)
			# Set given password
			new_user.set_password(user_form.cleaned_data['password'])
			new_user.save()
			profile = Profile.objects.create(user=new_user)
			return render(request, 'account/register_done.html', { 'new_user' : new_user })
	else:
		user_form = UserRegistrationForm()
	return render(request, 'account/register.html', { 'user_form': user_form })


@login_required
def edit(request):
	if request.method == 'POST':
		user_form = UserEditForm(instance=request.user,
								 data=request.POST)
		profile_form = ProfileEditForm(instance=request.user.profile,
									   data=request.POST,
									   files=request.FILES)
		if user_form.is_valid() and profile_form.is_valid():
			user_form.save()
			profile_form.save()
	else:
		user_form = UserEditForm(instance=request.user)
		profile_form = ProfileEditForm(instance=request.user.profile)
	return render(request, 'account/edit.html', { 'user_form' : user_form,
								 				  'profile_form' : profile_form })











# TEST VIEW
def test_home(request):
	return render(request, 'account/test_home.html', {})

deadlinekiller/account/templates/base.html
{% load static %}


<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>

	<!-- Bootstrap -->
	 <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
	
	<!-- Local css -->
	<link rel="stylesheet" type="text/css" href="{% static "account/base.css" %}">
</head>
<body>


<!-- BOOSTSTRAP TESTS 

	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="alert alert-primary" role="alert">
	  				nav
				</div>
			</div>
			
		</div>

		<div class="row">
			<div class="col-1">
				<div class="alert alert-primary" role="alert" >
					Home
				</div>
			</div>
			<div class="col-4 ml-auto">
				<div class="alert alert-primary" role="alert" >
					<input type="text" placeholder="Search" class="form-control">
				</div>
			</div>
		</div>

		<div class="row no-gutters">
			<div class="col-2">
				<div class="alert alert-primary" role="alert" style="min-height: 800px">
	  				This is a primary alert—check it out!
				</div>
			</div>
			<div class="col-8 ">
				<div class="alert alert-primary" role="alert" style="min-height: 800px">
	  				This is a primary alert—check it out!
				</div>
			</div>
			<div class="col-2">
				<div class="alert alert-primary" role="alert">
	  				This is a primary alert—check it out!
				</div>
			</div>
		</div>
	</div>



	<div class='container'>
		

		<div class="row">
			<div class="col-1">
				<div class="alert alert-primary" role="alert">
	  				This is a primary alert—check it out!
				</div>					
			</div>
			<div class="col-1">
				<div class="alert alert-secondary" role="alert">
	  				This is a primary alert—check it out!
				</div>					
			</div>
			<div class="col-1">
				<div class="alert alert-primary" role="alert">
	  				This is a primary alert—check it out!
				</div>					
			</div>
			<div class="col-1">
				<div class="alert alert-secondary" role="alert">
	  				This is a primary alert—check it out!
				</div>					
			</div>
			<div class="col-1">
				<div class="alert alert-primary" role="alert">
	  				This is a primary alert—check it out!
				</div>					
			</div>
			<div class="col-1">
				<div class="alert alert-secondary" role="alert">
	  				This is a primary alert—check it out!
				</div>					
			</div>
			<div class="col-1">
				<div class="alert alert-primary" role="alert">
	  				This is a primary alert—check it out!
				</div>					
			</div>
			<div class="col-1">
				<div class="alert alert-secondary" role="alert">
	  				This is a primary alert—check it out!
				</div>					
			</div>
			<div class="col-1">
				<div class="alert alert-primary" role="alert">
	  				This is a primary alert—check it out!
				</div>					
			</div>
			<div class="col-1">
				<div class="alert alert-secondary" role="alert">
	  				This is a primary alert—check it out!
				</div>					
			</div>
			<div class="col-1">
				<div class="alert alert-primary" role="alert">
	  				This is a primary alert—check it out!
				</div>					
			</div>
			<div class="col-1">
				<div class="alert alert-secondary" role="alert">
	  				This is a primary alert—check it out!
				</div>					
			</div>

		</div>
	

	</div>


	<div class='container-fluid'>
		

		<div class="row">
			<div class="col-1">
				<div class="alert alert-primary" role="alert">
	  				This is a primary alert—check it out!
				</div>					
			</div>
			<div class="col-1">
				<div class="alert alert-secondary" role="alert">
	  				This is a primary alert—check it out!
				</div>					
			</div>
			<div class="col-1">
				<div class="alert alert-primary" role="alert">
	  				This is a primary alert—check it out!
				</div>					
			</div>
			<div class="col-1">
				<div class="alert alert-secondary" role="alert">
	  				This is a primary alert—check it out!
				</div>					
			</div>
			<div class="col-1">
				<div class="alert alert-primary" role="alert">
	  				This is a primary alert—check it out!
				</div>					
			</div>
			<div class="col-1">
				<div class="alert alert-secondary" role="alert">
	  				This is a primary alert—check it out!
				</div>					
			</div>
			<div class="col-1">
				<div class="alert alert-primary" role="alert">
	  				This is a primary alert—check it out!
				</div>					
			</div>
			<div class="col-1">
				<div class="alert alert-secondary" role="alert">
	  				This is a primary alert—check it out!
				</div>					
			</div>
			<div class="col-1">
				<div class="alert alert-primary" role="alert">
	  				This is a primary alert—check it out!
				</div>					
			</div>
			<div class="col-1">
				<div class="alert alert-secondary" role="alert">
	  				This is a primary alert—check it out!
				</div>					
			</div>
			<div class="col-1">
				<div class="alert alert-primary" role="alert">
	  				This is a primary alert—check it out!
				</div>					
			</div>
			<div class="col-1">
				<div class="alert alert-secondary" role="alert">
	  				This is a primary alert—check it out!
				</div>					
			</div>

		</div>


	</div>



 END BOOTSTRAP TESTS -->


<!-- NAVBAR -->
<div class="container">
	<nav>
		<ul class="nav justify-content-end" id="nav_bar">
			{% if request.user.is_authenticated %}
				  <li class="nav-item">
				    <a class="nav-link" href="{% url 'deadlines:deadline_list' %}">Deadlines</a>
				  </li>
				  <li class="nav-item dropdown">
				    	<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Friends</a>
				   		 <div class="dropdown-menu">
				     		<a class="dropdown-item" href="{% url 'friends:friends_list' %}">Your friends</a>
				      		<a class="dropdown-item" href="{% url 'friends:friends_invitations' %}">Your invitations</a>
				      		
				      		
				      	<div class="dropdown-divider"></div>
				      		<a class="dropdown-item" href="{% url 'friends:connections' %}">Search friends</a>
				    	</div> 
				  </li>

				  <!-- Old friends
				  <li class="nav-item">
				    <a class="nav-link" href="{% url 'friends:connections' %}">Friends</a>
				  </li> -->
				  <li class="nav-item">
				    <a class="nav-link" href="{% url 'teams:team_list' %}">Teams</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link active" href="{% url 'account:logout' %}"> {{ request.user.username }} | Logout</a>
				  </li>
			  {% else %}
				  <li class="nav-item">
				    <a class="nav-link active" href="{% url 'account:login' %}"> Login</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link active" href="{% url 'account:register' %}"> Sign up</a>
				  </li>

			  {% endif %}

		</ul>
	</nav>










	
<!-- OLD NAVBAR
	<div class="row">
		<div class="col-12">
			<nav>
				<ul>
					{% if request.user.is_authenticated %}
						<li>You are logged in as: {{ request.user.username }} | <a href="{% url 'account:logout' %}">logout</a>.</li>
						<li><a href="{% url 'deadlines:deadline_list' %}">Deadlines</a></li>
						<li><a href="{% url 'teams:team_list' %}">Teams</a></li>
						<li><a href="{% url 'friends:connections' %}">Friends</a></li>
					{% else %}
						<li><a href="{% url 'account:login' %}">Login</a></li>
						<li><a href="{% url 'account:register' %}">Sign up</a></li>
					{% endif %}
				</ul>
			</nav>
		</div>
	</div> -->


	<!-- Django messages -->
	{% if messages %}
		<ul class="messages">
    	{% for message in messages %}
    		<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    	{% endfor %}
		</ul>
	{% endif %}


	<!-- Main Section-->
	<h1>DEADLINEKILLER | base html page</h1>

	{% block content %}
	{% endblock %}

</div>

	<!-- Bootstrap -->
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

</body>
</html>

deadlinekiller/account/templates/home.html
{% extends 'base.html' %}

{% block title %}Deadline Killer Home {% endblock %}

{% block content %}
	<h2>Welcome to Deadline Killer App</h2>
	<p>We will help you with managing deadlins</p>
	{% if request.user.is_authenticated %}
		<p>Welcome {{user.username}}!</p>
	{% else %}
		<p><a href="{% url 'account:login' %}">Login</a> or <a href="{% url 'account:register' %}">Create</a> new account.</p>
	{% endif %}
{% endblock %}