deadlinekiller/deadlinekiller/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    # Home Page
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home_page'),

    # Apps Urls
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^deadlines/', include('deadlines.urls', namespace='deadlines')),
    url(r'^teams/', include('teams.urls', namespace='teams')),
    url(r'^friends/', include('friends.urls', namespace='friends')),
    

]

deadlinekiller/deadlines/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
	# Deadline CRUD

	# List view
    url(r'^$', views.deadline_list, name='deadline_list'),

    # Detail view
    url(r'^(?P<pk>\d+)/(?P<slug>[-\w]+)/$', views.deadline_detail, name='deadline_detail'),

    # Create
    url(r'^deadline-create/$', views.deadline_create, name='deadline_create'),

    # Update
    url(r'^deadline-update/(?P<pk>\d+)/(?P<slug>[-\w]+)/$', views.deadline_update, name='deadline_update'),
    
    # Delete
    url(r'^deadline-delete/(?P<pk>\d+)/(?P<slug>[-\w]+)/$', views.deadline_delete, name='deadline_delete'),

   
]

deadlinekiller/teams/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
	
    url(r'^team-list/$', views.TeamListView.as_view(), name='team_list'),
    url(r'^team-detail/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.TeamDetailView.as_view(), name='team_detail'),
    url(r'^team-create/$', views.TeamCreateView.as_view(), name='team_create'),
    url(r'^team-delete/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.TeamDeleteView.as_view(), name='team_delete'),

    #Adding to the team and removing from the team (user profile)
    url(r'^team-add/$', views.AddToTheTeamView.as_view(), name='add_to_the_team'),
    

]

deadlinekiller/deadlines/models.py
from django.contrib.auth.models import User
from django.conf import settings
from django.db import models
from django.urls import reverse

from account.models import Profile
from teams.models import Team



class Project(models.Model):
	pass



class Deadline(models.Model):
	'''
	This model represents deadline.
	The focal point of the app.
	'''
	PRIORITIES = (
			('1', 'highest'),
			('2', 'high'),
			('3', 'medium'),
			('4', 'low'),
			('5', 'lowest'),

		)

	name = models.CharField(max_length=80)
	slug = models.SlugField(max_length=80)
	description = models.CharField(max_length=200)
	project = models.ForeignKey(Project, related_name='deadlines', blank=True, null=True)
	author = models.ForeignKey(User, related_name='deadlines', blank=True, null=True)
	deadline_date = models.DateTimeField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	priority = models.CharField(max_length=80, choices=PRIORITIES, default='3')	

	# M2M
	team = models.ManyToManyField(Team, blank=True, related_name='teams')
	participant = models.ManyToManyField(Profile, blank=True, related_name='participants')


	def __str__(self):
		return '{} created by {}'.format(self.name, self.author)

	def get_absolute_url(self):
		return reverse('deadlines:deadline_detail', args=[self.pk, self.slug])

deadlinekiller/deadlines/forms.py
from django import forms
 

from .models import Deadline


class DeadlineForm(forms.ModelForm):
	class Meta:
		model = Deadline
		fields = ('name', 'description', 'project', 'deadline_date', 'priority',)
		

deadlinekiller/deadlines/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.text import slugify

from .forms import DeadlineForm
from .models import Deadline
from account.models import Profile
from teams.models import Team


@login_required
def deadline_list(request):
	deadline_list = Deadline.objects.filter(author=request.user)
	deadlines_total = deadline_list.count()
	paginator = Paginator(deadline_list, 10) 
	page = request.GET.get('page')
	try:
		deadlines = paginator.page(page)
	except PageNotAnInteger:
        # If page is not an integer, deliver first page.
		deadlines = paginator.page(1)
	except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
		deadlines = paginator.page(paginator.num_pages)
	return render(request, 'deadlines/deadline_list.html', { 'deadlines' : deadlines,
															 'deadlines_total' : deadlines_total,
															 'page' : page })


@login_required
def deadline_detail(request, pk, slug):
	# Get deadline
	deadline = get_object_or_404(Deadline, pk=pk, slug=slug)

	# Take form data
	team_pk = request.POST.get('team_pk')
	operation = request.POST.get('operation')

	# Add new team to this deadline
	if team_pk and operation == 'add':
		team_to_add = get_object_or_404(Team, pk=team_pk)
		deadline.team.add(team_to_add)
	# Remove team from deadline
	elif team_pk and operation == 'remove':
		team_to_remove = get_object_or_404(Team, pk=team_pk)
		deadline.team.remove(team_to_remove)
	
	# Get teams user created
	user_teams = Team.objects.filter(creator=request.user) 

	# Get teams user (profile) is participant of
	teams_participant = request.user.profile.team.all()
	all_user_teams = user_teams | teams_participant
	all_user_teams = all_user_teams.distinct()

	# Remove teams that are already in this deadline
	for team in all_user_teams:
		if team in deadline.team.all():
			all_user_teams = all_user_teams.exclude(pk=team.pk)



	return render(request, 'deadlines/deadline_detail.html', {'deadline' : deadline,
															  'all_user_teams' : all_user_teams})


@login_required
def deadline_create(request):
	if request.method == 'POST':
		deadline_form = DeadlineForm(request.POST)
		
		if deadline_form.is_valid():
			new_form = deadline_form.save(commit=False)
			# Assigne logged in user to a deadline (as an author)
			new_form.author = request.user
			# Create a slug from name field
			new_form.slug = slugify(new_form.name)
			new_form.save()
			messages.success(request, 'New deadline was created. Tick tock, tick tock...')
			return redirect('deadlines:deadline_list')

	else:
		deadline_form = DeadlineForm()
	return render(request, 'deadlines/deadline_create.html', {'deadline_form' : deadline_form})


@login_required
def deadline_update(request, pk, slug):
	deadline = get_object_or_404(Deadline, pk=pk, slug=slug)
	if request.method == 'POST':
		deadline_form = DeadlineForm(instance=deadline, data=request.POST)
		if deadline_form.is_valid():
			deadline_form.save()
			messages.success(request, '{} deadline was updated successfully.'.format(deadline.name))
			return redirect(deadline)
	else:
		deadline_form = DeadlineForm(instance=deadline)

	return render(request, 'deadlines/deadline_update.html', {'deadline' : deadline,
															  'deadline_form' : deadline_form})


@login_required
def deadline_delete(request, pk, slug):
	deadline = get_object_or_404(Deadline, pk=pk, slug=slug)
	deadline.delete()
	messages.success(request, '{} deadline was deleted successfully.'.format(deadline.name))
	return redirect('deadlines:deadline_list')
	

deadlinekiller/deadlines/templates/deadlines/deadline_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Create deadline{% endblock %}

{% block content %}
	
	<h1>Create deadline</h1>
	<p>Fill the form below to create deadline.</p>
	
	<form  action="" method="post">
		{{ deadline_form|crispy }}
		{% csrf_token %}
		<p><input type="submit" value="Create deadline"></p>
	</form>

{% endblock %}

deadlinekiller/deadlines/templates/deadlines/deadline_detail.html
{% extends 'base.html' %}


{% block title %}{{ deadline.name }}{% endblock %}



{% block content %}


	<div class="row">
		
		<div class="col-6">
			<h2>Deadline: {{ deadline.name }}</h2>
			<h2><span class="badge badge-warning">{{ deadline.deadline_date }}</span></h2>
			<p>Priority: {{ deadline.priority }}</p>
			<p>{{ deadline.description }}</p>
			<p>Created: {{ deadline.created }}</p>
			<p>Updated: {{ deadline.updated }}</p>
		</div>
		

		<div class="col-3">
			<h3>Actions: </h3>
			<p><a href="{% url 'deadlines:deadline_update' deadline.pk deadline.slug %}">Edit</a> this deadline.</p>
			<p><a href="{% url 'deadlines:deadline_delete' deadline.pk deadline.slug %}">Delete</a> this deadline.</p>
			<p>All deadlines <a href="{% url 'deadlines:deadline_list' %}">here</a>.</p>
		</div>
			

		<div class="col-3">
			<h3>Manage:</h3>
			{% if all_user_teams %}
				<p>Add team to this deadline.</p>
					{% for team in all_user_teams %}
						<div class="card" style="width: 18rem;">
							 <div class="card-body">
							 	<a href="{{ team.get_absolute_url }}">{{ team }}</a>
								<form action="" method="post">
									<input type="hidden" name="operation" value="add">
									<input type="hidden" name="team_pk" value="{{ team.pk }}">
									<input type="hidden" name="deadline_pk" value="{{ deadline.pk }}">
									{% csrf_token %}
									<input type="submit" value="Add to a deadline" class="btn btn-primary">
								</form>
							</div>
						</div>
					{% endfor %}
			{% else %}
				<p>All your teams are in this deadline.</p>
			{% endif %}
				<p><a href="#">Add participant to this deadline</a></p>			
		</div>


	</div>


	<div class="row">
		

		<div class="col-6">
		<h3>Teams of this deadline:</h3>
			<ul>
				{% for team in deadline.team.all %}
					<li>
						<a href="{{ team.get_absolute_url }}"> {{ team }}</a>
						<form action="" method="post" style="display: inline-block;">
							<input type="hidden" name="operation" value="remove">
							<input type="hidden" name="team_pk" value="{{ team.pk }}">
							{% csrf_token %}
							<input type="submit" value="remove" class="btn btn-danger">
						</form>
					</li>
					
				{% empty %}
					<p>No teams in this deadline. Add some.</p>
				{% endfor %}
			</ul>
			
		</div>


		<div class="col-6">
			<h3>Participants:</h3>
			<p>list of all deadline participants</p>
		</div>


	</div>


{% endblock %}

deadlinekiller/deadlines/templates/deadlines/deadline_list.html
{% extends 'base.html' %}


{% block title %}Deadline list{% endblock %}



{% block content %}
	<div class="row">
		

			<div class="col-8">
				<h1>All your deadlines</h1>
				<p><small>You have {{ deadlines_total }} active deadlines now.</small></p>
				
					{% for deadline in deadlines %}
								<div class="{% if deadline.priority == '1' %}
											card text-white bg-danger mb-3
										{% elif deadline.priority == '2' %} 
											card text-white bg-warning mb-3
										{% elif deadline.priority == '3' %} 
											card text-white bg-dark mb-3
										{% elif deadline.priority == '4' %} 
											card text-white bg-secondary mb-3
										{% else %}
											card bg-light mb-3
										{% endif %}" 
										style="max-width: 18rem;">
										
							  	<div class="card-header">
							  		{{ deadline.deadline_date }}
							  	</div>
							  		<div class="card-body">
							    		<h5 class="card-title">

							    			{{ deadline.name }}
							    		</h5>
							    		<p class="card-text">
							    			{{ deadline.description|truncatewords:10 }}
							    			<br/>
							    			<a href="{{ deadline.get_absolute_url }}" class="card-link">Details here.</a>
							    		</p>
							  		</div>
							  	</div>



						 <!--
						<li>
							<a href="{{ deadline.get_absolute_url }}">{{ deadline.name }}</a> | created: {{ deadline.created }}
							<p>Priority: {{ deadline.priority }}</p>
						</li> -->
					{% empty %}
						<h1>Sorry, you don't have deadlines yet</h1>
					{% endfor %}
				
			</div>


			<div class="col-4">
				<h2>New deadline?</h2>
				<p><a href="{% url 'deadlines:deadline_create' %}">Create</a> new deadline.</p>
			</div>
	</div>


	<div class="row">
		<div class="col-12">
			<!-- pagination -->
			{% include 'pagination.html' with page=deadlines %}
		</div>
	</div>


{% endblock %}

deadlinekiller/deadlines/templates/deadlines/deadline_update.html
{% extends 'base.html' %}

{% block title %}Update deadline{% endblock %}

{% block content %}
	
	<h1>Update deadline</h1>
	<p>Fill the form below to update deadline:  {{ deadline.name }}.</p>
	
	<form  action="" method="post">
		{{ deadline_form.as_p }}
		{% csrf_token %}
		<p><input type="submit" value="Update deadline"></p>
	</form>

{% endblock %}